#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 4
#define NRF_LOG_DEFERRED 0
#define NRF_LOG_FILTERS_ENABLED 1
#define NRF_LOG_USES_COLORS 1

#define NRF_LOG_BACKEND_RTT_ENABLED 1
#define NRF_LOG_BACKEND_RTT_TEMP_BUFFER_SIZE 64
#define NRF_LOG_BACKEND_RTT_TX_RETRY_CNT 3
#define NRF_LOG_BACKEND_RTT_TX_RETRY_DELAY_MS 1

#define THREAD_PANID 0xABCD
#define THREAD_CHANNEL 24

#define BUTTON_ENABLED 1

#define SAADC_ENABLED 1
#define SAADC_CONFIG_RESOLUTION 3
#define SAADC_CONFIG_LP_MODE 1

#define SPI_ENABLED 1
#define SPI1_ENABLED 1

#define TWI_ENABLED 1
#define TWI0_ENABLED 1
#define TWI_DEFAULT_CONFIG_CLR_BUS_INIT 1

#define APP_SCHEDULER_ENABLED 1
#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_USE_SCHEDULER 1

#define NRF_SDH_BLE_LOG_ENABLED 0
#define NRF_SDH_LOG_ENABLED 0
#define NRF_SDH_SOC_LOG_ENABLED 0

// for app_button
#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4

// clock for ot
#define NRF_CLOCK_ENABLED 1

// for ot
#define NRFX_NVMC_ENABLED 1

#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_FPU_SUPPORT_ENABLED 1
#define POWER_CONFIG_DEFAULT_DCDCEN 1

// mem manager for ot
#define MEM_MANAGER_ENABLED 1
#define MEMORY_MANAGER_SMALL_BLOCK_COUNT 64
#define MEMORY_MANAGER_SMALL_BLOCK_SIZE 64
#define MEMORY_MANAGER_MEDIUM_BLOCK_COUNT 16
#define MEMORY_MANAGER_LARGE_BLOCK_COUNT 4
#define MEMORY_MANAGER_LARGE_BLOCK_SIZE 512
#define MEMORY_MANAGER_XLARGE_BLOCK_COUNT 5
#define MEMORY_MANAGER_XLARGE_BLOCK_SIZE 2816

#define SEGGER_RTT_CONFIG_BUFFER_SIZE_UP 512
#define SEGGER_RTT_CONFIG_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_CONFIG_MAX_NUM_DOWN_BUFFERS 2
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 0

#endif //APP_CONFIG_H
